In [2]:
import DCA_square_loop as DCA
import BIG_HAMILTON as H
import numpy as np

In [3]:
# lattice parametrs
Nc = 4
Nf = 4
Nb = 4
L = int(np.sqrt(Nc))
T = np.array([[1, 1, 1, 1], [1, -1, -1, 1], [1, -1, 1, -1], [1, 1, -1, -1]]) / 2.
t = 1
V = 1
mu = 0
DCA.U = 4

# k-meshgrid parametrs
N = 10000

# matsubara grid parametrs
DCA.n = 100
DCA.beta = 1

In [4]:
G0_K,P0_K=DCA.get_start_GFs()

In [5]:
U , mu, t_renorm, V_renorm, hybridization, gamma, ek, eq = DCA.get_parametrs(G0_K, P0_K)

In [6]:
U

7.2728182136139097

In [7]:
ek

array([-0.45312392, -0.40531337, -0.53538267, -0.53538267])

In [8]:
hybridization

array([-0.35818546, -0.47663085,  0.4762401 , -0.4762401 ])

In [9]:
V_renorm

1.2996912730164243

In [10]:
t_renorm

1.2666054223097947

In [11]:
gamma

array([ 0.00976978, -0.00221453, -0.00273747,  0.00273747])

In [15]:
np.eye(4,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [45]:
f = H.Hamiltonian(np.array([0,0,0,0]*2),np.array([0]*32),0,np.array([0,0,0,0]),np.eye(4,4)*0,0,0).matrix(4,4,4,2,2,2,2,3)

100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|
100% |########################################################################|


In [48]:
f.shape

(1254400, 1254400)

In [49]:
from scipy.sparse.linalg import eigs
[E,V] = eigs(f,k=12,which='SR')

In [50]:
E

array([-60.+0.j, -60.+0.j, -60.+0.j, -60.+0.j, -60.+0.j, -58.+0.j,
       -58.+0.j, -60.+0.j, -60.+0.j, -60.+0.j, -60.+0.j, -58.+0.j])